USE [master]
GO
/****** Object:  Database [PayRollSystem]    Script Date: 01/28/2014 16:45:09 ******/
CREATE DATABASE [PayRollSystem] ON  PRIMARY 
( NAME = N'PayRollSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\PayRollSystem.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PayRollSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\PayRollSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'PayRollSystem', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PayRollSystem].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [PayRollSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PayRollSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PayRollSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PayRollSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PayRollSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [PayRollSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PayRollSystem] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [PayRollSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PayRollSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PayRollSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PayRollSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PayRollSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PayRollSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PayRollSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PayRollSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PayRollSystem] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PayRollSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PayRollSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PayRollSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PayRollSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PayRollSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PayRollSystem] SET  READ_WRITE 
GO
ALTER DATABASE [PayRollSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [PayRollSystem] SET  MULTI_USER 
GO
ALTER DATABASE [PayRollSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PayRollSystem] SET DB_CHAINING OFF 